# permissions for end users to edit playbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbook-editor-role
rules:
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - playbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - playbooks/status
  verbs:
  - get
