# permissions for end users to view playbookruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbookrun-viewer-role
rules:
- apiGroups:
  - devops.hotwave.io
  resources:
  - playbookruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.hotwave.io
  resources:
  - playbookruns/status
  verbs:
  - get
