# permissions for end users to view playbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbook-viewer-role
rules:
- apiGroups:
  - devops.hotwave.io
  resources:
  - playbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.hotwave.io
  resources:
  - playbooks/status
  verbs:
  - get
