# permissions for end users to view taskruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskrun-viewer-role
rules:
- apiGroups:
  - devops.hotwave.io
  resources:
  - taskruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.hotwave.io
  resources:
  - taskruns/status
  verbs:
  - get
