# permissions for end users to edit tasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-editor-role
rules:
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - tasks/status
  verbs:
  - get
