# permissions for end users to edit taskruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskrun-editor-role
rules:
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - taskruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - taskruns/status
  verbs:
  - get
