# permissions for end users to view templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-viewer-role
rules:
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hotwave.io.hotwave.io
  resources:
  - templates/status
  verbs:
  - get
