# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/hotwave.io.hotwave.io_playbooks.yaml
- bases/hotwave.io.hotwave.io_pipelines.yaml
- bases/hotwave.io.hotwave.io_pipelineruns.yaml
- bases/hotwave.io.hotwave.io_playbookruns.yaml
- bases/hotwave.io.hotwave.io_tasks.yaml
- bases/hotwave.io.hotwave.io_taskruns.yaml
- bases/hotwave.io.hotwave.io_actions.yaml
- bases/hotwave.io.hotwave.io_templates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_playbooks.yaml
#- patches/webhook_in_pipelines.yaml
#- patches/webhook_in_pipelineruns.yaml
#- patches/webhook_in_playbookruns.yaml
#- patches/webhook_in_tasks.yaml
#- patches/webhook_in_taskruns.yaml
#- patches/webhook_in_actions.yaml
#- patches/webhook_in_templates.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_playbooks.yaml
#- patches/cainjection_in_pipelines.yaml
#- patches/cainjection_in_pipelineruns.yaml
#- patches/cainjection_in_playbookruns.yaml
#- patches/cainjection_in_tasks.yaml
#- patches/cainjection_in_taskruns.yaml
#- patches/cainjection_in_actions.yaml
#- patches/cainjection_in_templates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
